server:
  port: 8080
  tomcat:
    max-threads: 100

logging:
  config: classpath:logback-spring.xml
  level:
    learning: info

spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 1000
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    platform: mariadb
    url: jdbc:mysql://127.0.0.1:3306/thorn?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password:
    tomcat:
      max-active: 100
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 1
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
  #      web-stat-filter:
  #        enabled: true
  #        url-pattern: /*
  #        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
  #        session-stat-enable: true
  #        session-stat-max-count: 10
  #      stat-view-servlet:
  #        enabled: true
  #        url-pattern: /druid/*
  #        reset-enable: true
  #        login-username: admin
  #        login-password: 123
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  http:
    encoding:
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  #  application:
  #    name: BBS
  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: 'prometheus'
  #  metrics:
  #    tags:
  #      application: ${spring.application.name}
  mail:
    host: smtp.qq.com
    username: 1289713219@qq.com
    password: semmrjytsyyjbagi
    default-encoding: UTF-8
    test-connection: true
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672