system:
  path:
    replyimg: /run/media/thorn/Thorn Passport/毕设/img/replyImg/
    avator:  /run/media/thorn/Thorn Passport/毕设/img/
    replyImg: /run/media/thorn/Thorn Passport/毕设/img/replyImg/
  page:
    post: 8
    message: 3
    mypost: 10
    reply: 8
    history: 10
  period:
    reload: 1

shiro:
  static: /res/**,/favicon.ico,/img/**
  monitor: /actuator/**,/druid/**
  permissive: /
  force: /message
  noUser: /user/login,/user/reg

mail:
  fromMail:
    addr: 1289713219@qq.com


hotPoint:
  path:
    reload: /run/media/thorn/Thorn Passport/毕设/reload/
  period:
    #    单位：秒
    reload: 1
    #    单位：天
    refreshPeriod: 1
    #    单位：小时
    savePeriod: 1
  threshold: 3
  refreshTime: 02:00:00
  saveTaskThreadNum: 2